<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="VerTipoDeProducto.aspx.cs" Inherits="Vista.Tipos.VerTipoDeProducto" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 137px;
        }
        .auto-style3 {
            width: 173px;
        }
        .auto-style4 {
            width: 185px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td><h1>Ver tipos de productos</h1></td>
                </tr>
            </table>
        </div>
        <table class="auto-style1">
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
                <td class="auto-style4">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">Filtrar por cod</td>
                <td class="auto-style3">
                    <asp:TextBox ID="TB_Filtrar" runat="server"></asp:TextBox>
                </td>
                <td class="auto-style4">
                    <asp:Button ID="BT_Filtrar" runat="server" OnClick="BT_Filtrar_Click" Text="Filtrar" />
                </td>
                <td>
                    <asp:Button ID="BT_Todo" runat="server" Text="Todos" OnClick="BT_Todo_Click" />
                </td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
                <td class="auto-style4">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <table class="auto-style1">
            <tr>
                <td>
                    <asp:GridView ID="GV_Datos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="GV_Datos_RowDeleting" AutoGenerateEditButton="True" OnRowEditing="GV_Datos_RowEditing" OnRowCancelingEdit="GV_Datos_RowCancelingEdit" OnRowUpdating="GV_Datos_RowUpdating">
                        <Columns>
                            <asp:TemplateField HeaderText="Codigo Tipo de producto">
                                <EditItemTemplate>
                                    <asp:Label ID="LV_EditCod" runat="server" Text='<%# Bind("PK_CodTipoProducto_TP") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LV_CodTipoDeProducto" runat="server" Text='<%# Bind("PK_CodTipoProducto_TP") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="codigo animal">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DD_EditAnimal" runat="server" DataSourceID="SqlDataSource1" DataTextField="Animal_A" DataValueField="PK_CodAnimales_An">
                                        <asp:ListItem></asp:ListItem>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PetsConnectionString %>" SelectCommand="select PK_CodAnimales_An, (nombre_An+' '+NombreDeRaza_An) as 'Animal_A' from Animales"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LV_CodAnimales" runat="server" Text='<%# Bind("CodAnimales_Tp") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Tipo de producto">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DD_EditTdp" runat="server">
                                        <asp:ListItem>Comida</asp:ListItem>
                                        <asp:ListItem>Accesorios</asp:ListItem>
                                        <asp:ListItem>Ropa</asp:ListItem>
                                        <asp:ListItem>Higiene</asp:ListItem>
                                        <asp:ListItem>Salud</asp:ListItem>
                                    </asp:DropDownList>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LV_TipoDeProducto" runat="server" Text='<%# Bind("TipoDeProducto_Tp") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Descripcion">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TB_EditDesc" runat="server" Text='<%# Bind("Descripcion_TP") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LV_Descripcion" runat="server" Text='<%# Bind("Descripcion_TP") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
        </table>
    </form>
</body>
</html>
