<%@ Page Language="C#" MasterPageFile="/Root.Master" AutoEventWireup="true" CodeBehind="VerTipoDeProducto.aspx.cs" Inherits="Vista.Tipos.VerTipoDeProducto" %>


<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Categorías</h2>
    <div class="searchbox">
        <asp:TextBox ID="txtBuscar" placeholder="Buscar por código" runat="server"></asp:TextBox>
        <asp:Button ID="btnBuscar" CssClass="material-icons mdc-icon-button" OnClick="btnBuscar_Click" runat="server" Text="search" />
    </div>
    <asp:GridView ID="GV_Datos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="GV_Datos_RowDeleting" AutoGenerateEditButton="True" OnRowEditing="GV_Datos_RowEditing" OnRowCancelingEdit="GV_Datos_RowCancelingEdit" OnRowUpdating="GV_Datos_RowUpdating">
        <Columns>
            <asp:TemplateField HeaderText="Codigo Tipo de producto">
                <EditItemTemplate>
                    <asp:Label ID="LV_EditCod" runat="server" Text='<%# Bind("PK_CodTipoProducto_TP") %>'></asp:Label>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LV_CodTipoDeProducto" runat="server" Text='<%# Bind("PK_CodTipoProducto_TP") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="codigo animal">
                <EditItemTemplate>
                    <asp:DropDownList ID="DD_EditAnimal" runat="server" DataSourceID="SqlDataSource1" DataTextField="Animal_A" DataValueField="PK_CodAnimales_An">
                        <asp:ListItem></asp:ListItem>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PetsConnectionString %>" SelectCommand="select PK_CodAnimales_An, (nombre_An+' '+NombreDeRaza_An) as 'Animal_A' from Animales"></asp:SqlDataSource>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LV_CodAnimales" runat="server" Text='<%# Bind("CodAnimales_Tp") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tipo de producto">
                <EditItemTemplate>
                    <asp:DropDownList ID="DD_EditTdp" runat="server">
                        <asp:ListItem>Comida</asp:ListItem>
                        <asp:ListItem>Accesorios</asp:ListItem>
                        <asp:ListItem>Ropa</asp:ListItem>
                        <asp:ListItem>Higiene</asp:ListItem>
                        <asp:ListItem>Salud</asp:ListItem>
                    </asp:DropDownList>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LV_TipoDeProducto" runat="server" Text='<%# Bind("TipoDeProducto_Tp") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Descripcion">
                <EditItemTemplate>
                    <asp:TextBox ID="TB_EditDesc" runat="server" Text='<%# Bind("Descripcion_TP") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LV_Descripcion" runat="server" Text='<%# Bind("Descripcion_TP") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <asp:Label ID="lbl_mensaje_error" runat="server"></asp:Label>
</asp:Content>
