<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="VerTipoDeProducto.aspx.cs" Inherits="Vista.Tipos.VerTipoDeProducto" %>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plantilla</title>
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="/index.css" />
    <script src="/index.js"></script>
</head>

<body>
    <style>
        .template-field {
            max-width: 200px;
        }
    </style>
    <form id="form1" runat="server">
        <div class="contents">
            <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
            <header class="mdc-top-app-bar mdc-top-app-bar--fixed">
                <div class="mdc-top-app-bar__row">
                    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
                        <span class="mdc-top-app-bar__title" runat="server" id="spanPageTitle">PetShop</span>
                    </section>
                    <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
                        <asp:LinkButton ID="lbIniciarSesion" runat="server" OnClick="IniciarSesion" CssClass="mdc-button mdc-button--raised _header-important-btn mdc-top-app-bar__action-item">
                        <span class="mdc-button__ripple"></span>
                        <span class="mdc-button__label">Iniciar sesión</span>
                        </asp:LinkButton>
                        <asp:LinkButton ID="lbActualUser" OnClick="VerPerfilActual" runat="server" CssClass="mdc-button mdc-top-app-bar__action-item _header-profile-btn">
                            <span class="mdc-button__ripple"></span>
                            <span class="mdc-button__label"><b runat="server" id="lbAUNombre"></b>
                                <br>
                                <span runat="server" id="lbAURol"></span></span>
                        </asp:LinkButton>
                    </section>
                </div>
            </header>
            <main class="mdc-top-app-bar--fixed-adjust obj--main">
                <h2>Categorías</h2>
                <div class="searchbox">
                    <asp:TextBox ID="txtBuscar" placeholder="Buscar por código" runat="server"></asp:TextBox>
                    <asp:Button ID="btnBuscar" CssClass="material-icons mdc-icon-button" OnClick="btnBuscar_Click" runat="server" Text="search" />
                </div>
                <asp:GridView ID="GV_Datos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="GV_Datos_RowDeleting" AutoGenerateEditButton="True" OnRowEditing="GV_Datos_RowEditing" OnRowCancelingEdit="GV_Datos_RowCancelingEdit" OnRowUpdating="GV_Datos_RowUpdating">
                    <Columns>
                        <asp:TemplateField HeaderText="Codigo Tipo de producto">
                            <EditItemTemplate>
                                <asp:Label ID="LV_EditCod" runat="server" Text='<%# Bind("PK_CodTipoProducto_TP") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LV_CodTipoDeProducto" runat="server" Text='<%# Bind("PK_CodTipoProducto_TP") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="codigo animal">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DD_EditAnimal" runat="server" DataSourceID="SqlDataSource1" DataTextField="Animal_A" DataValueField="PK_CodAnimales_An">
                                    <asp:ListItem></asp:ListItem>
                                </asp:DropDownList>
                                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PetsConnectionString %>" SelectCommand="select PK_CodAnimales_An, (nombre_An+' '+NombreDeRaza_An) as 'Animal_A' from Animales"></asp:SqlDataSource>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LV_CodAnimales" runat="server" Text='<%# Bind("CodAnimales_Tp") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Tipo de producto">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DD_EditTdp" runat="server">
                                    <asp:ListItem>Comida</asp:ListItem>
                                    <asp:ListItem>Accesorios</asp:ListItem>
                                    <asp:ListItem>Ropa</asp:ListItem>
                                    <asp:ListItem>Higiene</asp:ListItem>
                                    <asp:ListItem>Salud</asp:ListItem>
                                </asp:DropDownList>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LV_TipoDeProducto" runat="server" Text='<%# Bind("TipoDeProducto_Tp") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Descripcion">
                            <EditItemTemplate>
                                <asp:TextBox ID="TB_EditDesc" runat="server" Text='<%# Bind("Descripcion_TP") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="LV_Descripcion" runat="server" Text='<%# Bind("Descripcion_TP") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
                <asp:Label ID="lbl_mensaje_error" runat="server"></asp:Label>
            </main>
            <aside class="mdc-snackbar">
                <div class="mdc-snackbar__surface" role="status" aria-relevant="additions">
                    <div class="mdc-snackbar__label" aria-atomic="false"></div>
                </div>
            </aside>
    </form>
</body>
</html>
