<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="/Root.Master" CodeBehind="Administrar.aspx.cs" Inherits="Vista.Animales.Administrar" %>
<%@ Import Namespace="Entidades" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Animales</h2>
    <div class="searchbox">
        <asp:TextBox ID="txtBuscar" placeholder="Buscar por código" runat="server"></asp:TextBox>
        <asp:Button ID="btnBuscar" CssClass="material-icons mdc-icon-button" OnClick="btnBuscar_Click" runat="server" Text="search" />
    </div>

    <asp:GridView ID="GV_Datos" CssClass="mdc-data-table" runat="server" OnSelectedIndexChanged="GV_Datos_SelectedIndexChanged" CellPadding="4" GridLines="None" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="GV_Datos_RowDeleting" AutoGenerateEditButton="True" OnRowCancelingEdit="GV_Datos_RowCancelingEdit" OnRowEditing="GV_Datos_RowEditing" OnRowUpdating="GV_Datos_RowUpdating">
        <alternatingrowstyle backcolor="White" />
        <columns>
            <asp:TemplateField HeaderText="Codigo de animal">
                <edititemtemplate>
                    <div class="mdc-data-table__cell">
                        <asp:Label ID="LV_EditCod" runat="server" Text='<%# Eval(Animal.Columns.Codigo) %>'></asp:Label>
                    </div>
                </edititemtemplate>
                <itemtemplate>
                    <div class="mdc-data-table__cell">
                        <asp:Label ID="LV_Cod_Animal" runat="server" Text='<%# Eval(Animal.Columns.Codigo) %>'></asp:Label>
                    </div>
                </itemtemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Nombre el Animal">
                <edititemtemplate>
                    <div class="mdc-data-table__cell">
                        <asp:TextBox ID="TB_EditNombre" runat="server" Text='<%# Eval(Animal.Columns.Nombre) %>'></asp:TextBox>
                    </div>
                </edititemtemplate>
                <itemtemplate>
                    <div class="mdc-data-table__cell">
                        <asp:Label ID="LV_NombreAnimal" runat="server" Text='<%# Eval(Animal.Columns.Nombre) %>'></asp:Label>
                    </div>
                </itemtemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Raza">
                <edititemtemplate>
                    <div class="mdc-data-table__cell">
                        <asp:TextBox ID="TB_EditRaza" runat="server" Text='<%# Eval(Animal.Columns.Raza) %>'></asp:TextBox>
                    </div>
                </edititemtemplate>
                <itemtemplate>
                    <div class="mdc-data-table__cell">
                        <asp:Label ID="LV_Raza" runat="server" Text='<%# Eval(Animal.Columns.Raza) %>'></asp:Label>
                    </div>
                </itemtemplate>
            </asp:TemplateField>
        </columns>
    </asp:GridView>
</asp:Content>
