<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="/Root.Master" CodeBehind="Administrar.aspx.cs" Inherits="Vista.Productos.Editar" %>

<%@ Import Namespace="Entidades" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Productos</h2>
    <div class="searchbox">
        <asp:TextBox ID="txtBuscar" placeholder="Buscar por código" runat="server"></asp:TextBox>
        <asp:Button ID="btnBuscar" CssClass="material-icons mdc-icon-button" OnClick="btnBuscar_Click" runat="server" Text="search" />
    </div>
    <asp:GridView CssClass="mdc-data-table" ID="grdProductos" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" CellPadding="4" GridLines="None" OnRowCancelingEdit="grdProductos_RowCancelingEdit" OnRowEditing="grdProductos_RowEditing" OnRowUpdating="grdProductos_RowUpdating" AllowPaging="True" AutoGenerateDeleteButton="True" OnPageIndexChanging="grdProductos_PageIndexChanging" OnRowDeleting="grdProductos_RowDeleting" PageSize="5">

        <Columns>
            <asp:TemplateField HeaderText="Codigo">
                <EditItemTemplate>
                    <asp:Label ID="lbl_eit_codigo" runat="server" Text='<%# Eval(Producto.Columns.Codigo_Prod) %>'></asp:Label>
                    <br />
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_codigo" runat="server" Text='<%# Eval(Producto.Columns.Codigo_Prod) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Proveedor">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Prov" runat="server" Text='<%# Eval(Producto.Columns.CUITProv) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Prov" runat="server" Text='<%# Eval(Producto.Columns.CUITProv) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tipo">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Tipo" runat="server" Text='<%# Eval(Producto.Columns.CodTipoProducto) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Tipo" runat="server" Text='<%# Eval(Producto.Columns.CodTipoProducto) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Nombre">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Nombre" runat="server" Text='<%# Eval(Producto.Columns.Nombre) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Nombre" runat="server" Text='<%# Eval(Producto.Columns.Nombre) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Marca">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Marca" runat="server" Text='<%# Eval(Producto.Columns.Marca) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Marca" runat="server" Text='<%# Eval(Producto.Columns.Marca) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Descripcion">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Desc" runat="server" Text='<%# Eval(Producto.Columns.Descripcion) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Desc" runat="server" Text='<%# Eval(Producto.Columns.Descripcion) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Stock">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Stock" runat="server" Text='<%# Eval(Producto.Columns.Stock) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_stock" runat="server" Text='<%# Eval(Producto.Columns.Stock) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Imagen">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Imagen" runat="server" Text='<%# Eval(Producto.Columns.Imagen) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Imagen" runat="server" Text='<%# Eval(Producto.Columns.Imagen) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Precio">
                <EditItemTemplate>
                    <asp:TextBox ID="txt_eit_Precio" runat="server" Text='<%# Eval(Producto.Columns.Precio) %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lbl_it_Precio" runat="server" Text='<%# Eval(Producto.Columns.Precio) %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
    <br />
    <br />
    <asp:Label ID="lbl_mensaje_error" runat="server"></asp:Label>
</asp:Content>
